CI: Add the possibility to run only one test also on Windows

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -7,6 +7,18 @@ on:
         description: 'Branch or tag of ocaml/ocaml to use as compiler'
         type: string
         default: '5.0.0-beta1'
+      only_test:
+        description: 'Only test to run (eg “src/array/lin_tests.exe”); whole suite is run if empty'
+        type: string
+        default: ''
+      seed:
+        description: 'Seed for the only test'
+        type: string
+        default: ''
+      repeats:
+        description: 'Number of test attempts'
+        type: string
+        default: '2'
 
 jobs:
   build:
@@ -14,6 +26,9 @@ jobs:
 
     env:
       COMPILER:  ${{ inputs.compiler }}
+      ONLY_TEST: ${{ inputs.only_test }}
+      SEED: ${{ inputs.seed }}
+      REPEATS: ${{ inputs.repeats }}
       QCHECK_MSG_INTERVAL: '60'
 
     steps:
@@ -55,6 +70,24 @@ jobs:
 
       - name: Build the test suite
         run: opam exec --switch=ci -- dune build
+        if: inputs.only_test == ''
 
       - name: Run the test suite
         run: opam exec --switch=ci -- dune runtest -j1 --no-buffer --display=quiet --cache=disabled --error-reporting=twice
+        if: inputs.only_test == ''
+
+      - name: Run only one test
+        run: |
+          $ErrorActionPreference = 'Continue'
+          $failures = 0
+          for($i = 1; $i -le "${env:REPEATS}"; $i++) {
+            if("${env:SEED}" -eq "") {
+              opam exec --switch=ci -- dune exec "${env:ONLY_TEST}" -- -v
+              if($? -eq 0) { $failures += 1 }
+            } else {
+              opam exec --switch=ci -- dune exec "${env:ONLY_TEST}" -- -v -s "${env:SEED}"
+              if($? -eq 0) { $failures += 1 }
+            }
+          }
+          echo "Test failed $failures times"
+        if: inputs.only_test != ''
